language: objective-c
osx_image: xcode11
before_install:
    - swift package resolve
    - gem install xcpretty
script:
    - swift package generate-xcodeproj
    - set -o pipefail && xcodebuild -project CombineValidations.xcodeproj -scheme CombineValidations-Package -destination 'platform=iOS Simulator,name=iPhone Xr,OS=13.0' -enableCodeCoverage YES clean build test | xcpretty
environment:
    CODECOV_TOKEN="cd76b802-708b-4805-91e9-f0f32cdd3a1e"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - gem install jazzy
  - make documentation
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local_dirs: docs
  on:
      branch: master
